### ISSUE TITLE
weird Sanskrit highlighting

### ISSUE THREAD

**Issue by eroux** [buda-base/buda-base#17]
It's probably a bug in lucene-sa but I don't have time to confirm that now so I'm just opening it here: 

http://library.bdrc.io/search?q=%22n%C4%81masa%E1%B9%85g%C4%ABti%22&lg=sa-x-iast&t=Work

shows some odd highlighting such as

![bugsa](https://user-images.githubusercontent.com/60868/60709599-207f8800-9f11-11e9-84e2-846e44ede345.png)

**Comment by berger-n** [comment]
another example:
![image](https://user-images.githubusercontent.com/33383857/60881130-52f8f000-a245-11e9-8d30-0a4ed59ec371.png)
